name: ML API Pipeline

on:
  push:
    branches:
      - main

jobs:
  model_training:
    name: Train Model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          echo "⚠️ Replace this with your actual model training command"
          # python scripts/train_model.py

  model_testing:
    name: Test Model
    runs-on: ubuntu-latest
    needs: model_training
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "⚠️ Replace this with your actual test command"
          # pytest tests/

  build_package:
    name: Build Python Package (.whl)
    runs-on: ubuntu-latest
    needs: model_testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install build tools
        run: pip install setuptools wheel

      - name: Build wheel
        run: |
          echo "⚠️ Ensure your setup.py is present in project root"
          python setup.py bdist_wheel
          ls -lh dist/

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: bikeshare-wheel
          path: dist/*.whl

  dockerize_api:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build_package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: bikeshare-wheel
          path: .

      - name: Move wheel to project root
        run: |
          mv bikeshare_model-*.whl ./bikeshare_model-0.0.1-py3-none-any.whl

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bikeshare-api:latest .

  push_dockerhub:
    name: Push Docker Image to DockerHub
    runs-on: ubuntu-latest
    needs: dockerize_api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bikeshare-api:latest .

      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bikeshare-api:latest
