name: ML API Pipeline

on:
  push:
    branches:
      - main

jobs:
  model_training:
    name: Train Model
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bikeshare_project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements/requirements.txt

      - name: Run training pipeline
        run: python bikeshare_model/train_pipeline.py

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: bikeshare_project/bikeshare_model/trained_models/bikeshare__model_output_v0.0.1.pkl


  model_testing:
    name: Test Model
    runs-on: ubuntu-latest
    needs: model_training
    defaults:
      run:
        working-directory: bikeshare_project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements/requirements.txt
          pip install -r requirements/test_requirements.txt

      - name: Download trained model artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: bikeshare_project/bikeshare_model/trained_models

      - name: Run tests
        run: pytest tests/
        
  build_package:
    name: Build Python Package (.whl)
    runs-on: ubuntu-latest
    needs: model_testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install build backend
        run: pip install build

      - name: Build wheel from pyproject.toml
        run: python -m build --wheel
        working-directory: bikeshare_project/bikeshare_project

      - name: Upload .whl artifact
        uses: actions/upload-artifact@v4
        with:
          name: bikeshare-wheel
          path: bikeshare_project/bikeshare_project/dist/*.whl
